export const GET_BUILDING_REQUEST = "GET_BUILDING_REQUEST"; 
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS"; 
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE"; 

export const ADD_BUILDING_REQUEST = "ADD_BUILDING_REQUEST"; 
export const ADD_BUILDING_SUCCESS = "ADD_BUILDING_SUCCESS"; 
export const ADD_BUILDING_FAILURE = "ADD_BUILDING_FAILURE"; 
