export const GET_BUILDING_REQUEST = "GET_BUILDING_REQUEST"; 
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS"; 
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE"; 

export const ADD_BUILDING_REQUEST = "ADD_BUILDING_REQUEST"; 
export const ADD_BUILDING_SUCCESS = "ADD_BUILDING_SUCCESS"; 
export const ADD_BUILDING_FAILURE = "ADD_BUILDING_FAILURE"; 

export const EDIT_BUILDING_REQUEST = "EDIT_BUILDING_REQUEST"; 
export const EDIT_BUILDING_SUCCESS = "EDIT_BUILDING_SUCCESS"; 
export const EDIT_BUILDING_FAILURE = "EDIT_BUILDING_FAILURE"; 

export const DELETE_BUILDING_REQUEST = "DELETE_BUILDING_REQUEST"; 
export const DELETE_BUILDING_SUCCESS = "DELETE_BUILDING_SUCCESS"; 
export const DELETE_BUILDING_FAILURE = "DELETE_BUILDING_FAILURE"; 
