export const GET_REGION_REQUEST = "GET_REGION_REQUEST"; 
export const GET_REGION_SUCCESS = "GET_REGION_SUCCESS"; 
export const GET_REGION_FAILURE = "GET_REGION_FAILURE"; 

export const ADD_REGION_REQUEST = "ADD_REGION_REQUEST"; 
export const ADD_REGION_SUCCESS = "ADD_REGION_SUCCESS"; 
export const ADD_REGION_FAILURE = "ADD_REGION_FAILURE"; 

export const EDIT_REGION_BYID_REQUEST = "EDIT_REGION_BYID_REQUEST"; 
export const EDIT_REGION_BYID_SUCCESS = "EDIT_REGION_BYID_SUCCESS"; 
export const EDIT_REGION_BYID_FAILURE = "EDIT_REGION_BYID_FAILURE"; 