export const GET_CLIENTS_REQUEST = "GET_CLIENTS_REQUEST"; 
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS"; 
export const GET_CLIENTS_FAILURE = "GET_CLIENTS_FAILURE"; 

export const ADD_CLIENTS_REQUEST = "ADD_CLIENTS_REQUEST"; 
export const ADD_CLIENTS_SUCCESS = "ADD_CLIENTS_SUCCESS"; 
export const ADD_CLIENTS_FAILURE = "ADD_CLIENTS_FAILURE"; 

export const EDIT_CLIENTS_BYID_REQUEST = "EDIT_CLIENTS_BYID_REQUEST"; 
export const EDIT_CLIENTS_BYID_SUCCESS = "EDIT_CLIENTS_BYID_SUCCESS"; 
export const EDIT_CLIENTS_BYID_FAILURE = "EDIT_CLIENTS_BYID_FAILURE"; 

export const DELETE_CLIENTS_BYID_REQUEST = "DELETE_CLIENTS_BYID_REQUEST"; 
export const DELETE_CLIENTS_BYID_SUCCESS = "DELETE_CLIENTS_BYID_SUCCESS"; 
export const DELETE_CLIENTS_BYID_FAILURE = "DELETE_CLIENTS_BYID_FAILURE"; 