export const GETCLIENTSREQUEST = "GETCLIENTSREQUEST"; 
export const GETCLIENTSSUCCESS = "GETCLIENTSSUCCESS"; 
export const GETCLIENTSFAILURE = "GETCLIENTSFAILURE"; 

export const ADDCLIENTSREQUEST = "ADDCLIENTSREQUEST"; 
export const ADDCLIENTSSUCCESS = "ADDCLIENTSSUCCESS"; 
export const ADDCLIENTSFAILURE = "ADDCLIENTSFAILURE"; 