export const GET_CONSULTANCIES_REQUEST = "GET_CONSULTANCIES_REQUEST";
export const GET_CONSULTANCIES_SUCCESS = "GET_CONSULTANCIES_SUCCESS";
export const GET_CONSULTANCIES_FAILURE = "GET_CONSULTANCIES_FAILURE";