export const GET_SITES_REQUEST = "GET_SITES_REQUEST"; 
export const GET_SITES_SUCCESS = "GET_SITES_SUCCESS"; 
export const GET_SITES_FAILURE = "GET_SITES_FAILURE"; 

export const ADD_SITES_REQUEST = "ADD_SITES_REQUEST"; 
export const ADD_SITES_SUCCESS = "ADD_SITES_SUCCESS"; 
export const ADD_SITES_FAILURE = "ADD_SITES_FAILURE"; 