export const GET_SITES_REQUEST = "GET_SITES_REQUEST"; 
export const GET_SITES_SUCCESS = "GET_SITES_SUCCESS"; 
export const GET_SITES_FAILURE = "GET_SITES_FAILURE"; 

export const ADD_SITES_REQUEST = "ADD_SITES_REQUEST"; 
export const ADD_SITES_SUCCESS = "ADD_SITES_SUCCESS"; 
export const ADD_SITES_FAILURE = "ADD_SITES_FAILURE"; 

export const EDIT_SITES_BYID_REQUEST = "EDIT_SITES_BYID_REQUEST"; 
export const EDIT_SITES_BYID_SUCCESS = "EDIT_SITES_BYID_SUCCESS"; 
export const EDIT_SITES_BYID_FAILURE = "EDIT_SITES_BYID_FAILURE"; 

export const DELETE_SITES_BYID_REQUEST = "DELETE_SITES_BYID_REQUEST"; 
export const DELETE_SITES_BYID_SUCCESS = "DELETE_SITES_BYID_SUCCESS"; 
export const DELETE_SITES_BYID_FAILURE = "DELETE_SITES_BYID_FAILURE"; 