export const GETCONSULTANCIESREQUEST = "GETCONSULTANCIESREQUEST";
export const GETCONSULTANCIESSUCCESS = "GETCONSULTANCIESSUCCESS";
export const GETCONSULTANCIESFAILURE = "GETCONSULTANCIESFAILURE";

export const ADDCONSULTANCIESREQUEST = "ADDCONSULTANCIESREQUEST";
export const ADDCONSULTANCIESSUCCESS = "ADDCONSULTANCIESSUCCESS";
export const ADDCONSULTANCIESFAILURE = "ADDCONSULTANCIESFAILURE";