export const GET_CONSULTANCIES_REQUEST = "GET_CONSULTANCIES_REQUEST";
export const GET_CONSULTANCIES_SUCCESS = "GET_CONSULTANCIES_SUCCESS";
export const GET_CONSULTANCIES_FAILURE = "GET_CONSULTANCIES_FAILURE";

export const ADD_CONSULTANCIES_REQUEST = "ADD_CONSULTANCIES_REQUEST";
export const ADD_CONSULTANCIES_SUCCESS = "ADD_CONSULTANCIES_SUCCESS";
export const ADD_CONSULTANCIES_FAILURE = "ADD_CONSULTANCIES_FAILURE";

export const GET_CONSULTANCIES_BYID_REQUEST = "GET_CONSULTANCIES_BYID_REQUEST";
export const GET_CONSULTANCIES_BYID_SUCCESS = "GET_CONSULTANCIES_BYID_SUCCESS";
export const GET_CONSULTANCIES_BYID_FAILURE = "GET_CONSULTANCIES_BYID_FAILURE";

export const EDIT_CONSULTANCIES_BYID_REQUEST = "EDIT_CONSULTANCIES_BYID_REQUEST";
export const EDIT_CONSULTANCIES_BYID_SUCCESS = "EDIT_CONSULTANCIES_BYID_SUCCESS";
export const EDIT_CONSULTANCIES_BYID_FAILURE = "EDIT_CONSULTANCIES_BYID_FAILURE";

export const DELETE_CONSULTANCIES_BYID_REQUEST = "DELETE_CONSULTANCIES_BYID_REQUEST";
export const DELETE_CONSULTANCIES_BYID_SUCCESS = "DELETE_CONSULTANCIES_BYID_SUCCESS";
export const DELETE_CONSULTANCIES_BYID_FAILURE = "DELETE_CONSULTANCIES_BYID_FAILURE";