export const GETCONSULTANCIESREQUEST = "GETCONSULTANCIESREQUEST";
export const GETCONSULTANCIESSUCCESS = "GETCONSULTANCIESSUCCESS";
export const GETCONSULTANCIESFAILURE = "GETCONSULTANCIESFAILURE";

export const ADDCONSULTANCIESREQUEST = "ADDCONSULTANCIESREQUEST";
export const ADDCONSULTANCIESSUCCESS = "ADDCONSULTANCIESSUCCESS";
export const ADDCONSULTANCIESFAILURE = "ADDCONSULTANCIESFAILURE";

export const GETCONSULTANCIESBYIDREQUEST = "GETCONSULTANCIESBYIDREQUEST";
export const GETCONSULTANCIESBYIDSUCCESS = "GETCONSULTANCIESBYIDSUCCESS";
export const GETCONSULTANCIESBYIDFAILURE = "GETCONSULTANCIESBYIDFAILURE";

export const EDITCONSULTANCIESBYIDREQUEST = "EDITCONSULTANCIESBYIDREQUEST";
export const EDITCONSULTANCIESBYIDSUCCESS = "EDITCONSULTANCIESBYIDSUCCESS";
export const EDITCONSULTANCIESBYIDFAILURE = "EDITCONSULTANCIESBYIDFAILURE";