export const GET_BINDER_REQUEST = "GET_BINDER_REQUEST"
export const GET_BINDER_SUCCESS = "GET_BINDER_SUCCESS"
export const GET_BINDER_FAILURE = "GET_BINDER_FAILURE"

export const ADD_BINDER_REQUEST = "ADD_BINDER_REQUEST"
export const ADD_BINDER_SUCCESS = "ADD_BINDER_SUCCESS"
export const ADD_BINDER_FAILURE = "ADD_BINDER_FAILURE"