export const GET_BINDER_REQUEST = "GET_BINDER_REQUEST"
export const GET_BINDER_SUCCESS = "GET_BINDER_SUCCESS"
export const GET_BINDER_FAILURE = "GET_BINDER_FAILURE"

export const ADD_BINDER_REQUEST = "ADD_BINDER_REQUEST"
export const ADD_BINDER_SUCCESS = "ADD_BINDER_SUCCESS"
export const ADD_BINDER_FAILURE = "ADD_BINDER_FAILURE"

export const DELETE_BINDER_REQUEST = "DELETE_BINDER_REQUEST"
export const DELETE_BINDER_SUCCESS = "DELETE_BINDER_SUCCESS"
export const DELETE_BINDER_FAILURE = "DELETE_BINDER_FAILURE"

export const EDIT_BINDER_REQUEST = "EDIT_BINDER_REQUEST"
export const EDIT_BINDER_SUCCESS = "EDIT_BINDER_SUCCESS"
export const EDIT_BINDER_FAILURE = "EDIT_BINDER_FAILURE"