export const GET_CONSULTANCY_DROPDOWN_REQUEST = "GET_CONSULTANCY_DROPDOWN_REQUEST";
export const GET_CONSULTANCY_DROPDOWN_SUCCESS = "GET_CONSULTANCY_DROPDOWN_SUCCESS";
export const GET_CONSULTANCY_DROPDOWN_FAILURE = "GET_CONSULTANCY_DROPDOWN_FAILURE";

export const GET_CLIENTS_DROPDOWN_REQUEST = "GET_CLIENTS_DROPDOWN_REQUEST";
export const GET_CLIENTS_DROPDOWN_SUCCESS = "GET_CLIENTS_DROPDOWN_SUCCESS";
export const GET_CLIENTS_DROPDOWN_FAILURE = "GET_CLIENTS_DROPDOWN_FAILURE";

export const GET_REGION_DROPDOWN_REQUEST = "GET_REGION_DROPDOWN_REQUEST";
export const GET_REGION_DROPDOWN_SUCCESS = "GET_REGION_DROPDOWN_SUCCESS";
export const GET_REGION_DROPDOWN_FAILURE = "GET_REGION_DROPDOWN_FAILURE";

export const GET_SITES_DROPDOWN_REQUEST = "GET_SITES_DROPDOWN_REQUEST";
export const GET_SITES_DROPDOWN_SUCCESS = "GET_SITES_DROPDOWN_SUCCESS";
export const GET_SITES_DROPDOWN_FAILURE = "GET_SITES_DROPDOWN_FAILURE";

export const GET_BINDER_DROPDOWN_REQUEST = "GET_BINDER_DROPDOWN_REQUEST";
export const GET_BINDER_DROPDOWN_SUCCESS = "GET_BINDER_DROPDOWN_SUCCESS";
export const GET_BINDER_DROPDOWN_FAILURE = "GET_BINDER_DROPDOWN_FAILURE";
