export const GET_CONSULTANCY_DROPDOWN_REQUEST = "GET_CONSULTANCY_DROPDOWN_REQUEST"; 
export const GET_CONSULTANCY_DROPDOWN_SUCCESS = "GET_CONSULTANCY_DROPDOWN_SUCCESS"; 
export const GET_CONSULTANCY_DROPDOWN_FAILURE = "GET_CONSULTANCY_DROPDOWN_FAILURE"; 

export const GET_CLIENTS_DROPDOWN_REQUEST = "GET_CLIENTS_DROPDOWN_REQUEST"; 
export const GET_CLIENTS_DROPDOWN_SUCCESS = "GET_CLIENTS_DROPDOWN_SUCCESS"; 
export const GET_CLIENTS_DROPDOWN_FAILURE = "GET_CLIENTS_DROPDOWN_FAILURE"; 